### ISSUE TITLE
Add option to disable gravatar, consider disabling by default

### ISSUE THREAD

**Issue by notr1ch** [getfider/fider#226]
Using gravatar reveals a user's email address publicly since it uses MD5 with no secret. This makes the "Your e-mail is private and will never be displayed to anyone." message untrue.

It also results in sending a user's full name to a 3rd party. Since it's only used for initials you could reduce the data shared to just initials.

More background info: https://r1ch.net/blog/gravatar-considered-harmful

**Comment by goenning** [comment]
I wasn't aware of this, thanks for reporting. Since the beginning the plan was to let the user decide whenever they want to upload a profile picture, use Gravatar or simply show the letter avatar.

It was the easiest and fastest way to show a picture, so it was the first to be implemented. Letter avatar came a few months later. Upload a picture is coming soon.

I'm now wondering if we should completely remove support for Gravatar. I'd rather implement a definitive solution than a on/off switch for such things. 

---

By the way, if you're self-hosting Fider, changing [this single line](https://github.com/getfider/fider/blob/602370a820ff488d6b78f4db106ca3e97b13d853/public/components/common/Gravatar.tsx#L25)  to `src={fallback}` is the quick&dirty way of removing Gravatar and fallback to letter avatar.

**Comment by goenning** [comment]
Just googled about this topic, seems like some people are doing a internal proxy within their application so that the md5 hash is not exposed on the HTML. This looks like an easy and secure alternative, although it might add a few milliseconds to the response time of avatars.
