### ISSUE TITLE
Gitlab OAuth throws Exception

### ISSUE THREAD

**Issue by azurewraith** [getfider/fider#489]
When attempting to authenticate to an instance of GitLab w/ a self-signed certificate I get a "Shoot, well this is unexpected" when trying to test the OAuth connection and in the fider logs I find the below:

```
ERROR [2018-08-17T21:11:18Z] [WEB] [42f53750-2a25-4cc5-82e3-6ef9129207d3] Error Trace:
- app/middlewares/setup.go:153
- interface conversion: error is *url.Error, not *oauth2.RetrieveError
```

Any ideas on how I could potentially workaround?

**Comment by goenning** [comment]
hey @azurewraith,

I just tried to follow their guides and had issues with it as well. On the docs, the authorize url is HTTPS and token url is HTTP, which in my case was the root cause. I fixed it by moving everything to HTTPS, but I'm not sure if it's the same issue you're facing.

I have updated our docs to include GitLab, can you confirm that you have the same setup? 

https://getfider.com/docs/configuring-oauth/

**Comment by goenning** [comment]
@azurewraith are you still having this issue? If so, can you please update to the `getfider/fider:master` image and see if there's a better error message? The latest version has some improvements on how we handle OAuth errors.
