### ISSUE TITLE
markdown preview

### ISSUE THREAD

**Issue by goenning** [getfider/fider#544]
**Source:** https://feedback.fider.io/posts/29/preview-of-markdown-field

**Problem:** Fider accepts markdown text on the textarea for a new idea and comment, but the users can't see how the text will look like until they submit it. 

**Solution:** We could implement something like GitHub, where there is a tab to preview the text. Ideally this should be made as a React component that we can use in both places. We already use `markdown-it` NPM package, so this is a front-end only task.

**Comment by ganesharulanantham** [comment]
@goenning will take it up

**Comment by goenning** [comment]
I remember having this issue before. Aside from `mage watch`, do you have many other things open? You can also increase max files with this: https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by ganesharulanantham** [comment]
@goenning thx for the help.
Landed pull request [https://github.com/getfider/fider/pull/562](https://github.com/getfider/fider/pull/562)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/getfider/fider/issues/544#issuecomment-549092505

@Stale, this is still a problem. I just posted a comment at [`ideas.obsproject.com/posts/2737`](https://ideas.obsproject.com/posts/2737/provide-a-replacement-for-the-deprecated-system-theme#:~:text=%3E%20Just%20as%20a%20note%2C,those%20are%20being%20publicly%20tracked?) with CommonMark blockquote syntax, which wasn't rendered. There was no way to determine this before I posted it.

It's rather ironic that even https://github.com/getfider/fider/pull/562#event-2785702656 was closed due to being stale. You should reconsider your usage of that bot.
