### ISSUE TITLE
Unhealthy container

### ISSUE THREAD

**Issue by andymelichar** [getfider/fider#720]
I can't get fider to fully boot and stay healthy when running under docker.

Used the standard docker-compose.yml to boot it up, both containers are created, no errors shown in log, but docker shows the status as unhealthy.

`                "Log": [
                    {
                        "Start": "2019-01-23T15:45:02.761610011-05:00",
                        "End": "2019-01-23T15:45:07.761741682-05:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (5s)"
                    },
`
I installed bash and connected into the container, and running ./fider ping does indeed sometimes take longer than 5 seconds to run. 

Any ideas on how to fix the healthcheck or what might be causing the performance issue?

**Comment by GottZ** [comment]
hm. i just upgraded postgresql from 9.6 to 11.1 and now it's healthy.. fider is still slow af though.. weird.
i'm on :master right now.

**Comment by andymelichar** [comment]
I tried upgrading to postgresql 11.1, still wouldn't start up and stay healthy.
To get around it, I just added a longer healthcheck timeout to the docker-compose.yml file:
```
    healthcheck:
      timeout: 10s
```

**Comment by GottZ** [comment]
what the actual F

```
/ # ps aux | grep fider | wc -l
3517
/ # ps aux | grep fider | wc -l
3519
/ # ps aux | grep fider | wc -l
3522
```

**Comment by goenning** [comment]
I don’t have any update, I’m not looking at it at the moment.

What if you run the container without the health check? Also try running Fider with WARN log level as mentioned on related GH Issue

**Comment by GottZ** [comment]
hm. warn seems to have fixed it for now. will monitor though

**Comment by goenning** [comment]
I got to the bottom of this issue. By default, Fider uses a pool of 6 connections to Postgres (can be configured). Each HTTP requests use a single transaction (which consumes a connection), so if you have 7 concurrent requests, the 7th needs to wait and that's all fine.

We write logs to both stdout and the database. To prevent the whole HTTP request transaction to fail if anything goes wrong with the logs, we use a separate connection for it. This process is synchronous, so the HTTP request has to wait until the log is written.

On a scenario of 6 concurrent requests, for any of these requests to complete, it needs to write the log, but we cannot open another database connection because the pool is already full. The result is that all 6 requests will never complete and new requests will be queued.

This also explains why increasing log level to WARN solves the problem :)

I've issued a PR that changes the logging process to be asynchronous, which has solved the problem. 

Docker image `getfider/fider:PR_725` has this fix if anyone is interested in testing it.
