### ISSUE TITLE
redirect user to new URL when post slug changes

### ISSUE THREAD

**Issue by goenning** [getfider/fider#741]
when visiting a post /posts/{number}/{slug}, if the given slug is different than slug that we have saved on the database, redirect the user to the new URL.

Example:

A user creates a post with the title "Hello World".
The URL os this post will be /posts/1/hello-world
Admin then renames the post to "Hello Wonderful World"
The new URL os this post will be /posts/1/hello-wonderful-world

If someone visits /posts/1/hello-world, we render the page. But for SEO purposes, we should redirect the user to the new URL.

**Comment by joshuabezaleel** [comment]
Hi @goenning ! If it's okay with you, I would like to ask a question on this.
I am still not sure by what you mean on "render the page but redirect the user to the new URL". Can you elaborate on this? Why do we have to render the page using the old/past URL (/posts/1/hello-world), and not executing the normal process of loading a webpage with the new/changed URL(/posts/1/hello-wonderful/world)? 

Thank you very much! Have a nice day :slightly_smiling_face:

**Comment by goenning** [comment]
hey @joshuabezaleel, that sentence was badly formatted. What I mean is that currently, it render the page if an old slug is used, but we should actually redirect to the new URL.

**Comment by joshuabezaleel** [comment]
Hey @goenning , I tried to get the Fider development environment running at my machine and I then I encountered an error of :
```
- app/middlewares/tenant.go:31
- failed to get first tenant (app/services/sqlstore/postgres/tenant.go:300)
- failed to execute trx.Get (app/pkg/dbx/dbx.go:277)
- pq: relation "tenants" does not exist
```

Is there already any existing solution to this? Thank you very much :slightly_smiling_face:

**Comment by goenning** [comment]
hey, there was an issue where mage watch was not running database migrations, it's now fixed on master. Please pull latest changes and try again.

**Comment by joshuabezaleel** [comment]
Hey @goenning , I am sorry if I am going to ask such a basic question since I am really new to Go.

Where do you recommend we should do the redirecting? Since the URL to be accessed can only be defined at the [routes.go](https://github.com/getfider/fider/blob/00c95eea7daab2f89fc0292cba3caa61645b60ae/app/cmd/routes.go), and there's no slug property at the [web.props](https://github.com/getfider/fider/blob/00c95eea7daab2f89fc0292cba3caa61645b60ae/app/handlers/post.go#L70) to be passed and then rendered.

**Comment by goenning** [comment]
that's no problem at all, ask as many questions as you want :)

I believe the best place to do it is at PostDetails from handlers/post.go, becuase on this function you have access to both old and new slug. What do you think?

**Comment by joshuabezaleel** [comment]
Thank you very much beforehand for a really kind understanding, @goenning !! :slightly_smiling_face: 

Before going deeper to the issue, I got a question beforehand though. I still can't make it work with `mage watch` like the video I attach below, but I can make fider run with the combination of `mage build` and `mage run`. 
Also, there's a line of `/bin/sh: 1: /home/jobel/go/src/github.com/getfider/fider/godotenv: not found` when I ran `mage watch` but I can't understand why since I have installed `go get github.com/joho/godotenv/cmd/godotenv/` correctly. 
Do you have any idea why this happens? 

Thank you very much! :)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/7043511/56799608-79f97580-6843-11e9-967d-686544e51048.gif)

**Comment by goenning** [comment]
What happens if you run `which godotenv`? Because Fider expects godotenv to be on your PATH

**Comment by joshuabezaleel** [comment]
Hi @goenning , really sorry for the late reply. `godotenv` seems to be already on the PATH because it shows the path when I ran the `which` command. 
![image](https://user-images.githubusercontent.com/7043511/58245720-a25f8b80-7d7f-11e9-89f4-3c76b6ddacee.png)
