### ISSUE TITLE
Oauth with KeyCloak

### ISSUE THREAD

**Issue by esgn** [getfider/fider#820]
Hello all,

I'm trying to use fider with an existing user database stored in a LDAP. Fider supports custom oauth, so I'm trying to put a keycloak instance on top of my ldap. Has anyone ever trider fider+keycloak ? Cannot get it to work yet. Found the client secret in keycloak client credentials but this does not seem to solve the problem.

Thanks for any help/advice

**Comment by esgn** [comment]
Made it. You can close the issue. Trouble was linked to domain names / ip discrepancies on my local network.

For the record here what was required to make fider work with KeyCloak : 

- In keycloak create client "fider" for the intended realm and get client secret in client "Credentials" tab
- In Fider set the following values for the new custom oauth provider
  - Client ID : fider
  - Client secret : the value generated by keycloak (e.g : 93e3ef33-a81a-4e06-abae-60ee1a350a81)
  - Authorize URL : http://keycloak.domain/auth/realms/ign/protocol/openid-connect/auth
  - Token URL : http://keycloak.domain/auth/realms/ign/protocol/openid-connect/token
  - Scope : I put "profile". A scope generated by default by keycloak for the fider client.
  - Profile API URL : http://keycloak.domain/auth/realms/ign/protocol/openid-connect/userinfo
  - JSON Path : ID = preferred_username / Name = name / Email = email

Will try with https and ssl certificates soon but all in all this solution works in order to use an pre-existing LDAP.

**Comment by vuongpd95** [comment]
For people who is gonna stumble here in the future.

I was trying to setup keycloak 25.0 with fider using docker-compose locally & to make it works, I needed to change a few things from esgn configs
- Authorize URL: `http://127.0.0.1:8080/relms/{relm-name}/protocol/openid-connect/auth`
- Token URL: `http://127.0.0.1:8080/relms/{relm-name}/protocol/openid-connect/token`
- Scope: I put `profile openid email`
- Profile API URL: `http://127.0.0.1:8080/relms/{relm-name}/protocol/openid-connect/userinfo`
- JSON Path, same as esgn

You can actually get the above urls by going to 

```
http://127.0.0.1:8082/realms/{relm-name}/.well-known/openid-configuration
```

Do note here is `127.0.0.1` instead of `localhost` because when I used `localhost`, I received this error in fider logs.

```
dial tcp [::1]:8082: connect: connection refused 
```
